config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    root to: "matches#home"
  end


  devise_for :users
  resources :users, except: [:update,:edit,:destroy]
  resources :matches, except: [:edit,:update,:destroy]

  namespace :api do
    resources :users, except: [:edit,:destroy]
    resources :matches, except: [:edit,:update,:destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :studenta, :class_name => 'User'
  belongs_to :studentb, :class_name => 'User'

  validates :day, presence: true

  def self.generate_matches(day=Date.today)
    Match.where(day:day).destroy_all

    students_array = []
    students_array = self.get_students
    uneven(students_array)
    students_array = self.get_students.shuffle

    selected_dates = (day-(students_array.count-2)..(day-1))

    remember_chosen_ones = []

    students_array.each_with_index do |student,index|
      break if students_array.count/2 == Match.where(day:day).count
      next if remember_chosen_ones.include? index
      remember_chosen_ones.push(index)
      students_array.each_with_index do |other_student,other_index|
        next if remember_chosen_ones.include? other_index
        if self.duplicates(student,other_student,selected_dates)
          remember_chosen_ones.push(other_index)
          Match.create(day:day,studenta_id:student,studentb_id:other_student)
          break
        end
        if other_index == (students_array.count)-1
          self.generate_matches(day)
        end
      end
    end
  end


  def self.duplicates(student,other_student, selected_dates)
    found_matches = []
    found_matches << Match.where(studenta_id:student, studentb_id:other_student, day: selected_dates).ids
    if found_matches == [[]]
      found_matches << Match.where(studenta_id:other_student, studentb_id:student, day: selected_dates).ids
      if found_matches == [[], []]
        return true
      end
    end
    return false
  end

  def self.uneven(students_array)
    dummy = User.find_by(name:"dummy")
    if students_array.length%2 == 1 && dummy
      Match.where(studenta_id:dummy).or(Match.where(studentb_id:dummy)).destroy_all
      dummy.destroy

    elsif students_array.length%2 == 1
      User.create(name:"dummy",password:"dummy1",email:"dummy@test.com",status:"student")
    end
  end

  def self.get_students
    return User.where(status:"student").all.ids
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
  # has_many :matches, primary_key: :studenta, dependent: :destroy
  # has_many :matches, primary_key: :studentb, dependent: :destroy

  validates :name, presence: true
  validates :status, presence: true
end

app/controllers/api/matches_controller.rb
class Api::MatchesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    render status: 200, json: {
      matches: Match.all
    }.to_json
  end

  def create
    Match.generate_matches(params[:day].to_date)
    matches = Match.where(day:params[:day])
    if matches.empty?
      render status: 422, json: {
        message: "Matches could not be created",
        errors: match.errors
      }.to_json
    else
      students = User.where(status:"student")
      render status: 201, json: {
        message: "Matches succesfully created",
        matches: matches,
        students: students,
      }.to_json
    end
  end
  private

end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  def index
    render status: 200, json: {
      users: User.all
    }.to_json
  end
  def show

  end
  def update
    user = get_user
    if user.status == "admin"
      user.status = "student"
    else
      user.status = "admin"
    end
    user.save

    render status: 200,  json:{status:user.status, id:user.id, notice:"status changed"}
  end
  private
  def get_user
    User.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :authenticate_user!
  def home
    if current_user.status == "admin"
      redirect_to matches_path
    elsif current_user.status == "student"
      match = get_student_match_today(current_user)
      redirect_to match_path(match)
    else
      new_user_session
    end
  end

  def index
    if current_user.status == "admin"
      @matches = Match.all
      @days = Match.select(:day).map(&:day).uniq
      @days.delete(Date.today)
      @matches_today = Match.where(day:Date.today)
      render :_indexadmin
    elsif current_user.status == "student"
      @matches = get_student_matches(current_user).where("day < ?", Date.today)
      render :_indexstudent
    else
      new_user_session
    end
  end

  def show
    if current_user.status == "admin"
      @matches = Match.where(day:Date.today)
      render :_showadmin
    elsif current_user.status == "student"
      matches = get_student_matches(current_user)
      @match = matches.find_by(day:Date.today)
      render :_showstudent
    else
      new_user_session
    end
  end

  def new
    if current_user.status == "admin"
      @match = Match.new
    else
      render :root
    end
  end

  def create
    Match.generate_matches(params[:match][:day].to_date)
  end

  private

  def get_student_matches(user)
    Match.where(studenta:user).or(Match.where(studentb:user))
  end

  def get_student_match_today(user)
    Match.where(studenta:user,day:Date.today).or(Match.where(studentb:user,day:Date.today))
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  def index
    @users = User.all
    if current_user.status == "student"
      redirect_to :root
    end
  end
  private
  def get_user
    User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Matcheur</title>
  <%= csrf_meta_tags %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>

<body >
  <%= render "shared/navbar" %>
  <div class="background_fade">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container space">
      <%= yield %>
    </div>

    <footer class="footer">
      <div class="container">
        <span class="text-muted">Matcheur by Robert and Anissa</span>
      </div>
    </footer>
  </div>
</body>
</html>

app/views/matches/_indexadmin.html.erb
<h1>All existing Matches</h1>

<h3> Matches for today</h3>
<ul>
  <% @matches_today.each do |match| %>
<li> <%=match.studenta.name%> is matched with <%= match.studentb.name %></li>
<% end %>
</ul>
<hr>
<h3>Matches for all days</h3>
<% @days.each do |day| %>
 <h4> <%= day.to_date %></h4>
  <ul>

  <% @matches.where(day:day).each do |match| %>
<li> <%=match.studenta.name%> is matched with <%= match.studentb.name %></li>
<% end %>
</ul>
<% end %>
<%= link_to "Back to todays match",root_path, class:"button buttonborder"%>

app/views/matches/_indexstudent.html.erb
<ul>
  <% @matches.each do |match| %>
<li> <%=match.studenta.name%> is matched with <%= match.studentb.name %> on day: <%=match.day.to_date%></li>
<% end %>
</ul>
<%= link_to "show todays match", root_path, class:"button" %>

app/views/matches/_showadmin.html.erb
<h1>matches for <%= @matches.first.day %> </h1>
<ul>
  <% @matches.each do |match| %>
  <li> <%=match.studenta.name%> is matched with <%= match.studentb.name %></li>
  <% end %>
</ul>

<%= button_to "See all matches",  matches_path %>

app/views/matches/_showstudent.html.erb
<h1> <%= Date.today %></h1>

<h2> <%= @match.studenta.name%> is matched with <%= @match.studentb.name%> </h2>
<%= link_to "previous matches", matches_path, class:"button" %>

app/views/matches/new.html.erb
<h2> Generate new matches for day:</h2>
<div class="formborder">
  <%= form_for @match do |m| %>
  <div class="field">
    <%= m.date_field :day, class: "form-control" %>
  </div>
  <div class="actions" id="generate_match">
    <%= m.submit "push button", class: "btn btn-primary" %>
  </div>
  <%end%>
</div>
<div id="generated_list">
  <hr>

</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top no_margin">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Matcheur", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <% if !user_signed_in? %>
        <li><%= link_to "Log In", new_user_session_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
          <% if current_user.status == "admin" %>
            <li><%= link_to "All Users", users_path, class:"btn-default buttonborder"  %></li>
            <li><%= link_to "Generate Matches", new_match_path, class:"btn-default buttonborder"  %></li>
          <%end%>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/index.html.erb
<h1> User details</h1>


<div class="row">
  <table class="table" id="userTable">
  <thead class="thead-dark">
      <tr>
        <th scope="col" width="60%">Name</th>
        <th scope="col" width="20%">Status</th>
        <th scope="col" width="20%">Action</th>
      </tr>
    </thead>
    <tbody>

      <% @users.each do |user| %>
      <tr>
        <td><%=user.name%></td>
        <td><%= user.status%></td>
        <td>
          <button type="button" class="btn btn-default status-change" id=<%=user.id%> ><%=  user.status == "admin"? "Demote" : "Promote"%></button>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>